
if GetLocale() ~= "ptBR" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "Fundo" -- Needs review
L["2. Border"] = "Borda" -- Needs review
L["Addon Buttons"] = "Botões de Addon" -- Needs review
L["Always"] = "Sempre" -- Needs review
L["Backdrop Color"] = "Cor de fundo" -- Needs review
L["Background Color"] = "Cor de fundo" -- Needs review
L["Background Texture"] = "Textura do Fundo" -- Needs review
L["Border Color"] = "Cor da Borda" -- Needs review
L["Borders"] = "Bordas" -- Needs review
L["Border Texture"] = "Textura da Borda" -- Needs review
L["Boss Frames"] = "Frame do Boss" -- Needs review
L["Buttons"] = "Botões" -- Needs review
L["Calendar"] = "Calendário" -- Needs review
L["Challenge Mode Button (When Available)"] = "Botões do Modo desafio (Quando disponível)" -- Needs review
L["Circle"] = "Círculo" -- Needs review
L["Clear & start over"] = "Limpar e começar de novo" -- Needs review
L["Clock"] = "Relógio" -- Needs review
L["Coordinates"] = "Coordenadas" -- Needs review
L["Copy a Profile"] = "Copiar um perfil" -- Needs review
L["Copying this profile will reload your UI, are you sure?"] = "Copiar esse perfil vai recarregar a interface (UI), você tem certeza disso?" -- Needs review
L["Create a new border"] = "Criar uma nova borda" -- Needs review
L["Delete"] = "Deletar" -- Needs review
L["Delete a Profile"] = "Deletar um perfil" -- Needs review
L["Diamond"] = "Diamante" -- Needs review
L["Disable (opaque)"] = "Desabilitar (opacidade)" -- Needs review
L["Disable Rotation"] = "Desabilitar Rotação" -- Needs review
L["Dungeon Difficulty Indicator (When Available)"] = "Indicador de Dificuldade de Masmorra (Quando disponível)" -- Needs review
L["Dynamic Buttons"] = "Botões dinâmicos" -- Needs review
L["Enable"] = "Habilitar" -- Needs review
L["Enable Coordinates"] = "Habilitar Coordenadas" -- Needs review
L["Enable Hudmap"] = "Habilitar Hudmap" -- Needs review
L["Enter a name to create a new border. The name can be anything you like to help you identify that border."] = "Coloque um nome para criar uma nova borda. O nome pode ser qualquer coisa que você ache que vai lhe ajudar a identificar a borda." -- Needs review
L["Enter the full path to a texture to use. It's recommended that you use something like |cffff6600TexBrowser|r to find textures to use."] = "Entre o caminho inteiro da textura que deseja usar. É recomendado que você use alguma Addon como |cffff6600TexBrowser|r para achar a textura que deseja usar." -- Needs review
L["Font"] = "Fonte" -- Needs review
L["Font Color"] = "Cor da Fonte" -- Needs review
L["Font Size"] = "Tamanho da fonte" -- Needs review
L["Hide default border"] = "Esconder borda padrão" -- Needs review
L["HUD Color"] = "Cor do HUD" -- Needs review
L["Keybinding"] = "Tecla de atalho" -- Needs review
L["Let SexyMap control button visibility"] = "Deixar o SexyMap controlar a visibilidade dos botões" -- Needs review
L["Lock Button Dragging"] = "Bloquear o movimento de botões" -- Needs review
L["Lock Coordinates"] = "Bloquear a posição das coordenadas" -- Needs review
L["Lock Minimap"] = "Bloquear o minimapa" -- Needs review
L["Map Button"] = "Botão do mapa" -- Needs review
L["Name"] = "Nome" -- Needs review
L["Never"] = "Nunca" -- Needs review
L["New Mail Indicator (When Available)"] = "Indicador de nova carta" -- Needs review
L["Normal Opacity"] = "Opacidade normal" -- Needs review
L["Opacity"] = "Opacidade" -- Needs review
L["Open TexBrowser"] = "Abrir TexBrowser" -- Needs review
L["Profiles"] = "Perfil" -- Needs review
L["Reset Position"] = "Resetar posição" -- Needs review
L["Save current settings as preset..."] = "Salvar perfil em uso como..." -- Needs review
L["Scale"] = "Escala" -- Needs review
L["Show North Tag"] = "Mostrar o indicador do Norte no minimapa" -- Needs review
L["Show on minimap"] = "Mostrar no minimapa" -- Needs review
L["Static Rotation"] = "Rotação estática" -- Needs review
L["TexBrowser Not Installed"] = "TexBrowser não instalado" -- Needs review
L["Text Color"] = "Cor do texto" -- Needs review
L["Texture"] = "Textura" -- Needs review
L["Texture Options"] = "Opções de textura" -- Needs review
L["Text Width"] = "Largura do texto" -- Needs review
L["This will wipe out any current settings!"] = "Isso vai resetar todas as outras configurações" -- Needs review
L["Use Global Profile"] = "Usar Perfil Global" -- Needs review
L["Vertical Position"] = "Posição Vertical" -- Needs review
L["Visibility"] = "Visibilidade" -- Needs review
L["Voice Chat Button (When Available)"] = "Botão de chat de voz (quando possível)" -- Needs review
L["Width"] = "Largura" -- Needs review
L["Zoom In Button"] = "Botão aumentar o Zoom" -- Needs review
L["Zoom Out Button"] = "Botão diminuir o Zoom" -- Needs review


