
if GetLocale() ~= "ruRU" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "Фон" -- Needs review
L["2. Border"] = "Граница" -- Needs review
L["3. Artwork"] = "Художество (картина, заставка?)" -- Needs review
L["4. Overlay"] = "Наслоение" -- Needs review
L["5. Highlight"] = "Подсветка" -- Needs review
L["Add Blend (additive)"] = "Добавить Смесь (добавочную)" -- Needs review
L["Addon Buttons"] = "Кнопки аддона" -- Needs review
L["Allow SexyMap to assume drag ownership for buttons attached to the minimap. Turn this off if you have another mod that you want to use to position your minimap buttons."] = "Разрешить SexyMap двигать кнопки, присоединенные к мини-карте. Выключите это, если у Вы планируете делать это при помощи других средств." -- Needs review
L["Alpha Key (1-bit alpha)"] = "Главная клавиша" -- Needs review
L["Always"] = "Всегда" -- Needs review
L["Armored Man"] = "Человек в доспехах" -- Needs review
L["A static amount to rotate the texture by."] = "Значение для поворота текстуры " -- Needs review
L["Auto Zoom-Out Delay"] = "Задержка авто-отдаления" -- Needs review
L["Backdrop Color"] = "Цвет заднего фона" -- Needs review
L["Backdrop Insets"] = "Вставки на заднем плане" -- Needs review
L["Background Color"] = "Цвет фона" -- Needs review
L["Background/edge"] = "Фон/край" -- Needs review
L["Background Texture"] = "Текстура фона" -- Needs review
L["Blend Mode"] = "Режим смешения" -- Needs review
L["Blend (normal)"] = "Смесь (норма)" -- Needs review
L["Border Color"] = "Цвет границы" -- Needs review
L["Border Edge Size"] = "Размер края границы" -- Needs review
L["Borders"] = "Границы" -- Needs review
L["Border Texture"] = "Текстур границы" -- Needs review
L["Boss Frames"] = "Фреймы боссов" -- Needs review
L["Buttons"] = "Кнопки" -- Needs review
L["Calendar"] = "Календарь" -- Needs review
L["Capture Bars"] = "Бары захвата?" -- Needs review
L["Challenge Mode Button (When Available)"] = "Кнопка режим испытаний (если доступна)" -- Needs review
L["Circle"] = "Круг" -- Needs review
L["Clamp to screen"] = "Прикрепить к экрану" -- Needs review
L["Clear & start over"] = "Очистить и начать сначала" -- Needs review
L["Clear the current borders and start fresh"] = "Очистить текущие границы и начать заново" -- Needs review
L["Clock"] = "Часы" -- Needs review
L["Coordinates"] = "Координаты" -- Needs review
L["Create a new border"] = "Создать новую границу" -- Needs review
L["Current Borders"] = "Текущие границы" -- Needs review
L["Delete"] = "Удалить" -- Needs review
L["Diamond"] = "Бриллиант" -- Needs review
L["Disable (opaque)"] = "Отключить (непрозрачность)" -- Needs review
L["Disable Rotation"] = "Отключить поворот" -- Needs review
L["Drag Radius"] = "Радиус перетягивания" -- Needs review
L["Dungeon Difficulty Indicator (When Available)"] = "Индикатор сложности подземелий (если доступен)" -- Needs review
L["Dynamic Buttons"] = "Динамические кнопки" -- Needs review
L["Enable"] = "Включить" -- Needs review
L["Enable a HUD minimap. This is very useful for gathering resources, but for technical reasons, the HUD map and the normal minimap can't be shown at the same time. Showing the HUD map will turn off the normal minimap."] = "Включить HUD-миникарту. Это очень удобно для добывания ресурсов, но, по техническим причинам, HUD-миникарта и обычная миникарта не могут отображаться одновременно. Включение HUD-миникарты выключит обычную миникарту." -- Needs review
L["Enable Coordinates"] = "Включить координаты" -- Needs review
L["Enable Hudmap"] = "Включить HUD-карту" -- Needs review
L["Enable Minimap Fader"] = "Включить затухание миникарты" -- Needs review
L["Enable Movers"] = "Включить ползунки" -- Needs review
L["Font Size"] = "Размер шрифта" -- Needs review


